
```{r}
library(dplyr)
library(purrr)
library(stringr)
```


``` {r}
add_returns <- function(df) {
  
  #Lag is value from previous day
  df <- df |>
    mutate(daily_return = (adjusted / lag(adjusted)) - 1,
           daily_return = ifelse(is.na(daily_return), 0, daily_return),
           cumulative_return = cumprod(1 + daily_return) - 1)
           

  #Save data to a csv
  #write_csv(df, file = paste0("/Users/jackson/Documents/finance/data/stocks/", ticker, ".csv"))
  
  return(df)
}

stock_data_returns <- map(stock_data, add_returns)
```

# Change names of DF to ticker name
```{r}

stock_data_tickers <- stock_data_returns |> map(pluck, "symbol")

for (x in seq_along(stock_data_returns)) {
  # Get the ticker symbol from the first column of the corresponding tibble
  ticker <- pluck(stock_data_tickers[[x]])[1]
  
  # Rename the tibble in stock_data_returns using the ticker symbol
  names(stock_data_returns)[x] <- ticker
}

stock_data_returns <- lapply(stock_data_returns, function(df) {
  if (!is.null(df)) {
    mutate(df, symbol = as.character(symbol))
  } else {
    NULL
  }
})

stock_data_test <- map(names(stock_data_returns), ~ str_remove(., "\\.csv"))


```

# Industry stocks
```{r}
sec_df <- read_csv("/Users/jackson/Documents/finance/data/big_stock_sectors.csv")

indus_df <- sec_df |> filter(Sector == "Industrial")
health_df <- sec_df |> filter(Sector == "Healthcare")
it_df <- sec_df |> filter(Sector == "Information Technology")
comm_df <- sec_df |> filter(Sector == "Communications")
staples_df <- sec_df |> filter(Sector == "Staples")
discr_df <- sec_df |> filter(Sector == "Discretionary")
util_df <- sec_df |> filter(Sector == "Utilities")
fin_df <- sec_df |> filter(Sector == "Financial")
restate_df <- sec_df |> filter(Sector == "Real Estate")
energy_df <- sec_df |> filter(Sector == "Energy")
```


# Top industry returns
``` {r}
indus_top_returns <- function(df, top_n) {
  
  indus_df <- df |>
    select(Ticker) |>
    pull(Ticker)
  
  indus_data <- stock_data_returns[indus_df]
  combined_indus_data <- reduce(indus_data, bind_rows)
  
  combined_indus_data |>
  group_by(symbol) |>
  summarize(cum_ret = last(cumulative_return, na.rm = T)) |>
  arrange(desc(cum_ret)) |> head(top_n)
  
}

industrial <- indus_top_returns(indus_df, 20)
it <- indus_top_returns(it_df)
health <- indus_top_returns(health_df)
communications <- indus_top_returns(comm_df)
staples <- indus_top_returns(staples_df, 20)
discretionary <- indus_top_returns(discr_df, 20)
utilities <- indus_top_returns(util_df)
financial <- indus_top_returns(fin_df, 20)
real_estate <- indus_top_returns(restate_df, 20)
energy <- indus_top_returns(energy_df, 20)
```